apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: basic-pipeline
spec:
  params:
    - name: oc_project
      type: string
      description: name of the oc_project
  tasks:
  - name: task1
    taskRef:
      name: task1
    params:
    - name: oc_project
      value: $(params.oc_project)
  - name: task2
    taskRef:
      name: task2
    conditions:
    - conditionRef: "condition-1"
      params:
        - name: "project"
          value: $(params.oc_project)
