apiVersion: tekton.dev/v1alpha1
kind: Task
metadata: 
  name: task2
spec:
  steps:
      - name: conditional-echo
        image: quay.io/openshift/origin-cli:latest
        command: ["/bin/bash", "-c"]
        args:
          - |-
            echo This is step 2
